# Generated by Django 2.2.4 on 2021-03-26 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_wall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msg_posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_messages', to='app_wall.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments_for_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='app_wall.Message')),
                ('comments_on_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_comments', to='app_wall.User')),
            ],
        ),
    ]
