# Generated by Django 2.2.4 on 2021-03-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_wall', '0002_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments_on_user',
            new_name='comments_by_user',
        ),
    ]
