# Generated by Django 2.2.4 on 2021-03-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_wall', '0005_auto_20210328_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='msg_posted_by',
            new_name='message_posted_by',
        ),
    ]
